version: '3.1'

services:
  # NodeJS Service
  monannonce-node:
    container_name:  "monannonce-API-nodejs"
    build:
      context: ./
      dockerfile: Dockerfile
    command: 'node ace serve --watch'
    depends_on:
#      - 'monannonce_postgresql'
       - 'monannonce-mailhog'
    links:
#      - "monannonce_postgresql:monannonce_postgresql"
       - 'monannonce-mailhog:mailhog'
    environment:
      - NODE_ENV=development
    volumes:
      - './:/home/app:rw'
    ports:
      - "3333:3333"
    networks:
      - default
    expose:
      - "3333"
    working_dir: '/home/app/monannonce'
  monannonce-mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui